import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import NavBar from "@/components/NavBar";
import ContextProvider from "@/context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeTom = "dark";
  return (
    <html lang="en">
      <body>
        <Theme appearance="dark">
          <ContextProvider>
            <NavBar />
            {children}
          </ContextProvider>
        </Theme>
      </body>
    </html>
  );
}
