import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeTom = 'dark';
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Theme appearance={themeTom}>
          {children}
        </Theme>
      </body>
    </html>
  );
}
